### ISSUE TITLE
BUG??

### ISSUE THREAD

**Issue by Miftakya** [YinFinance/Bug-Bounty#3]
Describe the bug
Hello sir, I found some inappropriate amounts in the addition of liquidity

First I want to try adding liquidity to tUSDC/TUSDT.
After that I saw the amount They did not match what it should be,
There are 3 options tUSDC/tUSDT I tried them all and all amounts I found different
![IMG_20210805_172917_652](https://user-images.githubusercontent.com/38547614/128542906-bf359b6f-bd63-43cb-90df-d815839578ea.jpg)
![IMG_20210805_172914_654](https://user-images.githubusercontent.com/38547614/128542920-5a52f6d0-0a45-4e43-badd-ae84d467a6a2.jpg)
![IMG_20210805_172910_638](https://user-images.githubusercontent.com/38547614/128542943-b712b5a9-57a2-4734-afe2-f3a6ff006650.jpg)

**Comment by YinFinanceMaker** [comment]
Actually, this is not a BUG, the difference is because the liquidity assets of the CHI strategy is different.
